language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script: generate
after_success:
  - git remote add 50cm $REMOTE
  - git config user.name shundroid
  - git config user.email shundroidk@gmail.com
  - git add .
  - git commit -m "generated"
  - git push -f 50cm master:site
